%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/humble/.*$
%global __requires_exclude_from ^/opt/ros/humble/.*$

Name:           ros-humble-ros-core
Version:        0.9.3
Release:        3%{?dist}%{?release_suffix}
Summary:        ROS ros_core package

License:        Apache License 2.0
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-humble-ament-cmake
Requires:       ros-humble-ament-cmake-auto
Requires:       ros-humble-ament-cmake-gmock
Requires:       ros-humble-ament-cmake-gtest
Requires:       ros-humble-ament-cmake-pytest
Requires:       ros-humble-ament-cmake-ros
Requires:       ros-humble-ament-index-cpp
Requires:       ros-humble-ament-index-python
Requires:       ros-humble-ament-lint-auto
Requires:       ros-humble-ament-lint-common
Requires:       ros-humble-class-loader
Requires:       ros-humble-common-interfaces
Requires:       ros-humble-launch
Requires:       ros-humble-launch-ros
Requires:       ros-humble-launch-testing
Requires:       ros-humble-launch-testing-ament-cmake
Requires:       ros-humble-launch-testing-ros
Requires:       ros-humble-launch-xml
Requires:       ros-humble-launch-yaml
Requires:       ros-humble-pluginlib
Requires:       ros-humble-rcl-lifecycle
Requires:       ros-humble-rclcpp
Requires:       ros-humble-rclcpp-lifecycle
Requires:       ros-humble-rclpy
Requires:       ros-humble-ros-environment
Requires:       ros-humble-ros2cli-common-extensions
Requires:       ros-humble-ros2launch
Requires:       ros-humble-rosidl-default-generators
Requires:       ros-humble-rosidl-default-runtime
Requires:       ros-humble-sros2
Requires:       ros-humble-sros2-cmake
Requires:       ros-humble-ros-workspace
BuildRequires:  ros-humble-ament-cmake
BuildRequires:  ros-humble-ros-workspace
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%description
A package to aggregate the packages required to use publish / subscribe,
services, generate messages and other core ROS concepts.

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/humble/setup.sh" ]; then . "/opt/ros/humble/setup.sh"; fi
mkdir -p .obj-%{_target_platform} && cd .obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/humble" \
    -DAMENT_PREFIX_PATH="/opt/ros/humble" \
    -DCMAKE_PREFIX_PATH="/opt/ros/humble" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
%if !0%{?with_tests}
    -DBUILD_TESTING=OFF \
%endif
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/humble/setup.sh" ]; then . "/opt/ros/humble/setup.sh"; fi
%make_install -C .obj-%{_target_platform}

%if 0%{?with_tests}
%check
# Look for a Makefile target with a name indicating that it runs tests
TEST_TARGET=$(%__make -qp -C .obj-%{_target_platform} | sed "s/^\(test\|check\):.*/\\1/;t f;d;:f;q0")
if [ -n "$TEST_TARGET" ]; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/humble/setup.sh" ]; then . "/opt/ros/humble/setup.sh"; fi
CTEST_OUTPUT_ON_FAILURE=1 \
    %make_build -C .obj-%{_target_platform} $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files
/opt/ros/humble

%changelog
* Tue Apr 19 2022 Steven! Ragnarök <steven@openrobotics.org> - 0.9.3-3
- Autogenerated by Bloom

* Tue Feb 08 2022 Steven! Ragnarök <steven@openrobotics.org> - 0.9.3-2
- Autogenerated by Bloom

