%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/iron/.*$
%global __requires_exclude_from ^/opt/ros/iron/.*$

Name:           ros-iron-desktop
Version:        0.10.0
Release:        3%{?dist}%{?release_suffix}
Summary:        ROS desktop package

License:        Apache License 2.0
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-iron-action-tutorials-cpp
Requires:       ros-iron-action-tutorials-interfaces
Requires:       ros-iron-action-tutorials-py
Requires:       ros-iron-angles
Requires:       ros-iron-composition
Requires:       ros-iron-demo-nodes-cpp
Requires:       ros-iron-demo-nodes-cpp-native
Requires:       ros-iron-demo-nodes-py
Requires:       ros-iron-depthimage-to-laserscan
Requires:       ros-iron-dummy-map-server
Requires:       ros-iron-dummy-robot-bringup
Requires:       ros-iron-dummy-sensors
Requires:       ros-iron-examples-rclcpp-minimal-action-client
Requires:       ros-iron-examples-rclcpp-minimal-action-server
Requires:       ros-iron-examples-rclcpp-minimal-client
Requires:       ros-iron-examples-rclcpp-minimal-composition
Requires:       ros-iron-examples-rclcpp-minimal-publisher
Requires:       ros-iron-examples-rclcpp-minimal-service
Requires:       ros-iron-examples-rclcpp-minimal-subscriber
Requires:       ros-iron-examples-rclcpp-minimal-timer
Requires:       ros-iron-examples-rclcpp-multithreaded-executor
Requires:       ros-iron-examples-rclpy-executors
Requires:       ros-iron-examples-rclpy-minimal-action-client
Requires:       ros-iron-examples-rclpy-minimal-action-server
Requires:       ros-iron-examples-rclpy-minimal-client
Requires:       ros-iron-examples-rclpy-minimal-publisher
Requires:       ros-iron-examples-rclpy-minimal-service
Requires:       ros-iron-examples-rclpy-minimal-subscriber
Requires:       ros-iron-image-tools
Requires:       ros-iron-intra-process-demo
Requires:       ros-iron-joy
Requires:       ros-iron-lifecycle
Requires:       ros-iron-logging-demo
Requires:       ros-iron-pcl-conversions
Requires:       ros-iron-pendulum-control
Requires:       ros-iron-pendulum-msgs
Requires:       ros-iron-quality-of-service-demo-cpp
Requires:       ros-iron-quality-of-service-demo-py
Requires:       ros-iron-ros-base
Requires:       ros-iron-rqt-common-plugins
Requires:       ros-iron-rviz-default-plugins
Requires:       ros-iron-rviz2
Requires:       ros-iron-teleop-twist-joy
Requires:       ros-iron-teleop-twist-keyboard
Requires:       ros-iron-tlsf
Requires:       ros-iron-tlsf-cpp
Requires:       ros-iron-topic-monitor
Requires:       ros-iron-turtlesim
Requires:       ros-iron-ros-workspace
BuildRequires:  ros-iron-ament-cmake
BuildRequires:  ros-iron-ros-workspace
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%description
A package which extends 'ros_base' and includes high level packages like
vizualization tools and demos.

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/iron/setup.sh" ]; then . "/opt/ros/iron/setup.sh"; fi
mkdir -p .obj-%{_target_platform} && cd .obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/iron" \
    -DAMENT_PREFIX_PATH="/opt/ros/iron" \
    -DCMAKE_PREFIX_PATH="/opt/ros/iron" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
%if !0%{?with_tests}
    -DBUILD_TESTING=OFF \
%endif
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/iron/setup.sh" ]; then . "/opt/ros/iron/setup.sh"; fi
%make_install -C .obj-%{_target_platform}

%if 0%{?with_tests}
%check
# Look for a Makefile target with a name indicating that it runs tests
TEST_TARGET=$(%__make -qp -C .obj-%{_target_platform} | sed "s/^\(test\|check\):.*/\\1/;t f;d;:f;q0")
if [ -n "$TEST_TARGET" ]; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/iron/setup.sh" ]; then . "/opt/ros/iron/setup.sh"; fi
CTEST_OUTPUT_ON_FAILURE=1 \
    %make_build -C .obj-%{_target_platform} $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files
/opt/ros/iron

%changelog
* Thu Apr 20 2023 Steven! Ragnarök <steven@openrobotics.org> - 0.10.0-3
- Autogenerated by Bloom

* Wed Mar 22 2023 Steven! Ragnarök <steven@openrobotics.org> - 0.10.0-2
- Autogenerated by Bloom

